function [femregion]=create_dof(Dati,region)

ne=region.ne;
nedge=region.nedges;
degree = Dati.fem;

nln=0.5.*(degree+1).*(degree+2);

femregion=struct('fem',Dati.fem,...
    'nedges', nedge,...
    'nln',nln,...
    'ndof',nln*ne,...
    'ne',ne,...
    'nqn',Dati.nqn,...
    'coord',region.coord,...
    'BBox',region.BBox);
    
femregion.coords_element = region.coords_element;
femregion.connectivity = region.connectivity;
femregion.area = region.area;
femregion.max_kb = region.max_kb;

