function [DATI] = dati(name)

currentFolder = pwd;

pathMesh     = fullfile(currentFolder,'MeshGeneration');
pathMeshEx   = fullfile(currentFolder,'MeshExample');
pathFEspace  = fullfile(currentFolder,'FEspace');
pathAssembly = fullfile(currentFolder,'Assembly');
pathError    = fullfile(currentFolder,'Error');
pathPlot     = fullfile(currentFolder,'Plot');
% pathOther    = fullfile(currentFolder,'Other');

addpath(genpath(fullfile(pathMesh)));
addpath(genpath(fullfile(pathMeshEx)));
addpath(genpath(fullfile(pathFEspace)));
addpath(genpath(fullfile(pathAssembly)));
addpath(genpath(fullfile(pathError)));
addpath(genpath(fullfile(pathPlot)));
% addpath(genpath(fullfile(pathOther)));

lambda = 8.108108108108100e07;
mu = 3.378378378378378e06;

switch name
 case('Sysala-Valdman')
        DATI = struct( ...
            'type',              'verification', ...
            ... %Benchmark test case for error analysis
            'domain',            [0 10 0 10], ...
            ... % Domain bounds [xmin xmax ymin ymax],
            'bc',                'YXPX',...
            ... % boundary condition
            'Young',               1.0e7, ...
            'Poisson',             0.48, ...
            'Cohesion',            450.0, ...
            'Friction_angle',      pi/9, ...
            ... % Material properties 
            'fem',               2,...
            ... % Polynomial degree
            'penalty_coeff',     10,...
            ... % Penalty coefficient
            'theta',             0, ...
            ... % Theta (SIP, NIP, IIP)
            'source_1',         '0.*x.*y',...
            ... % Forcing term fx
            'source_2',          '0.*x.*y',...
            ... % Forcing term fy
            'source_t',          '0.*x.*y.*t',...
            ... % Forcing term ft --> f = ft * [fx;fy]
            'u0_x',              '0.*x.*y', ...
            ... % Initial condition ux(0)
            'u0_y',              '0.*x.*y', ...
            ... % Initial condition uy(0)
            'u_1_x',             '0.*x.*y',...
            ... % Initial condition ux(-dt)
            'u_1_y',             '0.*x.*y',...
            ... % Initial condition uy(-dt)
            'dir_1',             '0.*x.*y',...
            ... % Dirichlet condition ux
            'dir_2',             '-1.0*(y>9.9) + 0.*x.*y',...
            ... % Dirichlet condition uy
            'neu_1',             '0.*x.*y',...
            ... % Neumann condition on x direction
            'neu_2',             '0.*x.*y',...
            ... % Neumann condition on y direction
            'tol',               1e-10,...
            ... % Newton tolerance
            'max_it',            25, ...
            ... % max iterations
            'use_QN',            0, ...
            ... % 1 for Quasi-Newton, 0 for Newton
            'exact_sol_1',       '0.*x.*y.*t',...
            ... % Exact solution for conv test
            'exact_sol_2',       '0.*x.*y.*t',...
            ... % Exact solution for conv test
            'exact_grad1_x',     '0.*x.*y.*t',...
            ... % Gradient Exact solution for conv test
            'exact_grad1_y',     '0.*x.*y.*t',...
            ... % Gradient Exact solution for conv test
            'exact_grad2_x',     '0.*x.*y.*t',...
            ... % Gradient Exact solution for conv test
            'exact_grad2_y',     '0.*x.*y.*t',...
            ... % Gradient Exact solution for conv test
            'exact_grad1_t',     '0.*x.*y.*t',...
            ... % Time derivative Gradient Exact solution for conv test
            'exact_grad2_t',     '0.*x.*y.*t'); ...
            ... % Time derivative Exact solution for conv test
            
        
    case('Square')
        DATI = struct( ...
            'type',              'verification', ...
            ... %Benchmark test case for error analysis
            'domain',            [0 1 0 1], ...
            ... % Domain bounds [xmin xmax ymin ymax],
            'bc',                'YXPX',...
            ... % boundary condition
            'Young',               1e7, ...
            'Poisson',             0.48, ...
            'Cohesion',            450, ...
            'Friction_angle',      pi/9, ...
            ... % Material properties 
            'fem',               1,...
            ... % Polynomial degree
            'penalty_coeff',     10,...
            ... % Penalty coefficient
            'theta',              1, ...
            ... % Theta (SIP, NIP, IIP)
            'final_diri',         1,...
            ... % Dirichlet condition on left part of the top edge
            'source_1',           'pi^2*(9.121621621621613e7*sin(pi*x).*sin(pi*y) - 8.445945945945937e7*cos(pi*x).*cos(pi*y))',...            
            ... % Forcing term fx
            'source_2',          ' pi^2*(9.121621621621613e7*sin(pi*x).*sin(pi*y) - 8.445945945945937e7*cos(pi*x).*cos(pi*y))',...
            ... % Forcing term fy
            'dir_1',              ' 0.*x.*y',...
            ... % Dirichlet condition ux
            'dir_2',              '0.*y.*x',...
            ... % Dirichlet condition uy
            'neu_1x',             '- (1813753081081081*pi*cos(pi*x)*sin(pi*y))/536870912 - (1813753081081081*pi*cos(pi*y)*sin(pi*x))/536870912',...
            ... % Neumann condition on x direction
            'neu_1y',             '- (5441259243243239*pi*cos(pi*x)*sin(pi*y))/67108864 - (23578790054054037*pi*cos(pi*y)*sin(pi*x))/268435456',...
            ... % Neumann condition on y direction
            'neu_2x',             '(23578790054054037*pi*cos(pi*x)*sin(pi*y))/268435456 + (5441259243243239*pi*cos(pi*y)*sin(pi*x))/67108864',...
            ... % Neumann condition on x direction
            'neu_2y',             '(1813753081081081*pi*cos(pi*x)*sin(pi*y))/536870912 + (1813753081081081*pi*cos(pi*y)*sin(pi*x))/536870912',...
            ... % Neumann condition on y direction
            'neu_3x',             '(1813753081081081*pi*cos(pi*x)*sin(pi*y))/536870912 + (1813753081081081*pi*cos(pi*y)*sin(pi*x))/536870912',...
            ... % Neumann condition on x direction
            'neu_3y',             '(5441259243243239*pi*cos(pi*x)*sin(pi*y))/67108864 + (23578790054054037*pi*cos(pi*y)*sin(pi*x))/268435456',...
            ... % Neumann condition on y direction
            'neu_4x',             '- (23578790054054037*pi*cos(pi*x)*sin(pi*y))/268435456 - (5441259243243239*pi*cos(pi*y)*sin(pi*x))/67108864',...
            ... % Neumann condition on x direction
            'neu_4y',             '- (1813753081081081*pi*cos(pi*x)*sin(pi*y))/536870912 - (1813753081081081*pi*cos(pi*y)*sin(pi*x))/536870912',...
            ... % Neumann condition on y direction            'tol',               1e-2,...
            ... % Newton tolerance
            'max_it',            25, ...
            ... % max iterations
            'use_QN',            1, ...
            ... % 1 for Quasi-Newton, 0 for Newton
            'exact_sol_1',       'sin(pi*x).*sin(pi*y)+0.*t',...
            ... % Exact solution for conv test
            'exact_sol_2',       'sin(pi*x).*sin(pi*y)+ 0.*t',...
            ... % Exact solution for conv test
            'exact_grad1_x',     'pi*cos(pi*x).*sin(pi*y) + 0.*t',...
            ... % Gradient Exact solution for conv test
            'exact_grad1_y',     'pi*cos(pi*y).*sin(pi*x) + 0.*t',...
            ... % Gradient Exact solution for conv test
            'exact_grad2_x',     'pi*cos(pi*x).*sin(pi*y) + 0.*t',...
            ... % Gradient Exact solution for conv test
            'exact_grad2_y',     'pi*cos(pi*y).*sin(pi*x) + 0.*t');...
            ... % Gradient Exact solution for conv test       
        
        

        
         case('SquareDir')
        DATI = struct( ...
            'type',              'verification', ...
            ... %Benchmark test case for error analysis
            'domain',            [0 1 0 1], ...
            ... % Domain bounds [xmin xmax ymin ymax],
            'bc',                'DDDD',...
            ... % boundary condition
            'Young',               1e7, ...
            'Poisson',             0.48, ...
            'Cohesion',            450, ...
            'Friction_angle',      pi/9, ...
            ... % Material properties 
            'fem',               1,...
            ... % Polynomial degree
            'penalty_coeff',     10,...
            ... % Penalty coefficient
            'theta',              0, ...
            ... % Theta (SIP, NIP, IIP)
            'final_diri',         1,...
            ... % Dirichlet condition on left part of the top edge
            'source_1',         'pi^2*(9.121621621621613e7*sin(pi*x).*sin(pi*y) - 8.445945945945937e7*cos(pi*x).*cos(pi*y))',...            
            ... % Forcing term fx
            'source_2',          'pi^2*(9.121621621621613e7*sin(pi*x).*sin(pi*y) - 8.445945945945937e7*cos(pi*x).*cos(pi*y))',...
            ... % Forcing term fy
            'dir_1',             '10.0 + 0.*x.*y',...
            ... % Dirichlet condition ux
            'dir_2',             '10.0 +  0.*y.*x',...
            ... % Dirichlet condition uy
            'neu_1',             '0.*x.*y',...
            ... % Neumann condition on x direction
            'neu_2',             '0.*x.*y',...
            ... % Neumann condition on y direction
            'tol',               1e-10,...
            ... % Newton tolerance
            'max_it',            25, ...
            ... % max iterations
            'use_QN',            0, ...
            ... % 1 for Quasi-Newton, 0 for Newton
            'exact_sol_1',       'sin(pi*x).*sin(pi*y)+0.*t',...
            ... % Exact solution for conv test
            'exact_sol_2',       'sin(pi*x).*sin(pi*y)+ 0.*t',...
            ... % Exact solution for conv test
            'exact_grad1_x',     'pi*cos(pi*x).*sin(pi*y) + 0.*t',...
            ... % Gradient Exact solution for conv test
            'exact_grad1_y',     'pi*cos(pi*y).*sin(pi*x) + 0.*t',...
            ... % Gradient Exact solution for conv test
            'exact_grad2_x',     'pi*cos(pi*x).*sin(pi*y) + 0.*t',...
            ... % Gradient Exact solution for conv test
            'exact_grad2_y',     'pi*cos(pi*y).*sin(pi*x) + 0.*t');...
            ... % Gradient Exact solution for conv test
            
        
        
        
    case('Plate')
        DATI = struct( ...
            'type',              'verification', ...
            ... %Benchmark test case for error analysis
            'domain',            [0 2.0 0 3.6], ...
            ... % Domain bounds [xmin xmax ymin ymax],
            'bc',                'DDDDD',...
            ... % boundary condition
            'Young',               1e7, ...
            'Poisson',             0.48, ...
            'Cohesion',            450, ...
            'Friction_angle',      pi/9, ...
            ... % Material properties 
            'fem',               1,...
            ... % Polynomial degree
            'penalty_coeff',     10,...
            ... % Penalty coefficient
            'theta',              0, ...
            ... % Theta (SIP, NIP, IIP)
            'final_diri',         1,...
            ... % Dirichlet condition on left part of the top edge
            'source_1',         ' (136031481081080979*exp(-3*y).*cos(x))/536870912 - (186816567351351215*exp(-2*x).*cos(y))/536870912',...            
            ... % Forcing term fx
            'source_2',          '- (45343827027026993*exp(-2*x).*sin(y))/268435456 - (422604467891891585*exp(-3*y).*sin(x))/536870912',...
            ... % Forcing term fy
            'dir_1',             'exp(-2*x).*cos(y)',...
            ... % Dirichlet condition ux
            'dir_2',             'exp(-3*y).*sin(x)',...
            ... % Dirichlet condition uy
            'neu_1',             '0.*x.*y',...
            ... % Neumann condition on x direction
            'neu_2',             '0.*x.*y',...
            ... % Neumann condition on y direction
            'tol',               1e-2,...
            ... % Newton tolerance
            'max_it',            25, ...
            ... % max iterations
            'use_QN',            1, ...
            ... % 1 for Quasi-Newton, 0 for Newton
            'exact_sol_1',       'exp(-2*x).*cos(y)+0.*t',...
            ... % Exact solution for conv test
            'exact_sol_2',       'exp(-3*y).*sin(x)+ 0.*t',...
            ... % Exact solution for conv test
            'exact_grad1_x',     '-2*exp(-2*x).*cos(y) + 0.*t',...
            ... % Gradient Exact solution for conv test
            'exact_grad1_y',     '-exp(-2*x).*sin(y) + 0.*t',...
            ... % Gradient Exact solution for conv test
            'exact_grad2_x',     'exp(-3*y).*cos(x) + 0.*t',...
            ... % Gradient Exact solution for conv test
            'exact_grad2_y',     '-3*exp(-3*y).*sin(x) + 0.*t');...
            ... % Gradient Exact solution for conv test
            
         
    case('Corona')
        DATI = struct( ...
            'type',              'verification', ...
            ... %Benchmark test case for error analysis
            'domain',            [0 2 0 4], ...
            ... % Domain bounds
            'bc',                'NN',...
            ... % boundary condition
            'Young',               1e7, ...
            'Poisson',             0.48, ...
            'Cohesion',            450, ...
            'Friction_angle',      pi/9, ...
            ... % Material properties
            'fem',               2,...
            ... % Polynomial degree
            'penalty_coeff',     10,...
            ... % Penalty coefficient
            'theta',              1, ...
            ... % Theta (SIP, NIP, IIP)
            'final_diri',         1,...
            ... % Dirichlet condition on left part of the top edge
            'source_1',         '0.*x.*y',...
            ... % Forcing term fx
            'source_2',          '0.*x.*y',...
            ... % Forcing term fy
            'dir_1',             '0.*x.*y',...
            ... % Dirichlet condition ux
            'dir_2',             '0.*x.*y',...
            ... % Dirichlet condition uy
            'neu_1',             '0.*x.*y',...
            ... % Neumann condition on x direction
            'neu_2',             '((y<0)-(y>0))*(x.^2 - 16)*(x.^2 + y.^2 > 0.75^2)*6*10^4',...
            ... % Neumann condition on y direction
            'tol',               1e-2,...
            ... % Newton tolerance
            'max_it',            25, ...
            ... % max iterations
            'use_QN',            1, ...
            ... % 1 for Quasi-Newton, 0 for Newton
            'exact_sol_1',       '0.*x.*y+0.*t',...
            ... % Exact solution for conv test
            'exact_sol_2',       '0.*x.*y+0.*t',...
            ... % Exact solution for conv test
            'exact_grad1_x',     '0.*x.*y+0.*t',...
            ... % Gradient Exact solution for conv test
            'exact_grad1_y',     '0.*x.*y+0.*t',...
            ... % Gradient Exact solution for conv test
            'exact_grad2_x',     '0.*x.*y+0.*t',...
            ... % Gradient Exact solution for conv test
            'exact_grad2_y',     '0.*x.*y+0.*t');...
            ... % Gradient Exact solution for conv test
            
            
    
end